#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'
module RCSS
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     4,    12,     8,     9,     4,    15,    15,    13,    20,    12,
    12,    16,    18,    15,     7,    21,     4,     5,     4 ]

racc_action_check = [
     7,     7,     5,     7,    10,    10,    17,    10,    17,    11,
    14,    11,    14,    19,     4,    19,     3,     1,     0 ]

racc_action_pointer = [
    16,    17,   nil,    14,    10,     2,   nil,    -2,   nil,   nil,
     2,     6,   nil,   nil,     7,   nil,   nil,     3,   nil,    10,
   nil,   nil ]

racc_action_default = [
   -12,   -12,    -1,    -2,   -12,   -12,    -3,   -12,    22,    -4,
   -12,   -12,   -10,    -5,   -12,   -11,    -6,   -12,    -7,   -12,
    -8,    -9 ]

racc_goto_table = [
    10,     1,     2,    11,    17,     6,    14,    19 ]

racc_goto_check = [
     4,     1,     2,     3,     4,     2,     3,     4 ]

racc_goto_pointer = [
   nil,     1,     2,    -4,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,     3,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 7, :_reduce_none,
  1, 8, :_reduce_none,
  2, 8, :_reduce_none,
  3, 9, :_reduce_none,
  4, 9, :_reduce_none,
  4, 9, :_reduce_none,
  5, 9, :_reduce_none,
  5, 9, :_reduce_none,
  6, 9, :_reduce_none,
  1, 10, :_reduce_none,
  2, 10, :_reduce_none ]

racc_reduce_n = 12

racc_shift_n = 22

racc_token_table = {
  false => 0,
  :error => 1,
  :SELECTOR => 2,
  :PROPERTY => 3,
  :BEGINRULE => 4,
  :ENDRULE => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SELECTOR",
  "PROPERTY",
  "BEGINRULE",
  "ENDRULE",
  "$start",
  "stylesheet",
  "rules",
  "rule",
  "properties" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module RCSS
